### ISSUE TITLE
Hoja de estilo para Discourse

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/mozilla-hispano.org#208]
Hola,

¿Podemos tener una nueva hoja de estilo para las modificaciones en discourse?

Así en vez de meter directamente el css en el config de discourse simplemente le enlazamos la hoja.

/cc @stripTM @fjaguero

**Comment by fjaguero** [comment]
Ok, lo dejo en el siguiente PR con el #207

**Comment by stripTM** [comment]
¿Dentro del repositorio donde irá el archivo?

**Comment by nukeador** [comment]
Mi recomendación es hacer una carpeta ``discourse`` como tenemos para foro, wiki... y ahí meter de forma ordenada todo lo que tenga que ver (css, js, imágenes...)

Un saludo.

**Comment by fjaguero** [comment]
Ok, ¿hay que migrar código tuyo @stripTM?

**Comment by stripTM** [comment]
Ocurre como con lo de https://github.com/mozillahispano/mozilla-hispano.org/issues/207 el css debe estar en base de datos, se mete desde el administrador, este es el código a meter:
```css
#lienzo.discourse {
    overflow: visible;
    z-index: 10;
}
.discourse #menu {
    font-size: 1.4em;
}
.d-header {
    box-shadow: unset;
}
.docked .d-header {
    box-shadow: 0px 2px 4px -1px rgba(0, 0, 0, 0.25);
}
#main {
    z-index: 0;
    font-size: 1.4em;
}
.modal-open #main {
    z-index: 2000;
}
```
