### ISSUE TITLE
Versión mobile de discourse

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/mozilla-hispano.org#238]
Algunas cosas que veo en la versión mobile de discourse:

* No tenemos nuestra cabecerapie
* Los enlaces tardan en reaccionar mucho (Fx Android)
* Hay algunos elementos que hacen overflow por los laterales.

**Comment by pochy-ja** [comment]
Alguien está trabajando en esto?

**Comment by fjaguero** [comment]
No que yo sepa, lo dejo como ready para trabajar en ello.

**Comment by stripTM** [comment]
Según nos comentan en https://foro.mozilla-hispano.org/t/bugs-de-responsibilidad-en-el-foro-de-mozilla/21825/6 hay algunos problemas nuevos.

**Comment by stripTM** [comment]
Los que se comentaban al principio

>    No tenemos nuestra cabecerapie

He añadido sólo el pie, probé con la cabecera pero es demasiado grande y creo que no aporta tanto como para comerse tanto hueco.

>    Los enlaces tardan en reaccionar mucho (Fx Android)
>    Hay algunos elementos que hacen overflow por los laterales.

Esto creo que está ok, si veis algún caso pasarme la url.

Para las mejoras en el propio foro he añadido esto al css de móvil

```css
/* Separación en barra de color izquierda en categoría https://foro.mozilla-hispano.org/ */
.topic-list th:first-of-type, .topic-list td:first-of-type {
    padding-left: 5px;
}
/* Ocultar columna de categorías https://foro.mozilla-hispano.org/c/discusion-general */
th.category, td.category {
	display: none;
}
```
